### ISSUE TITLE
Populate string-based scheme with NaN values

### ISSUE THREAD

**Issue by ATriantafyllopoulos** [audeering/audformat#68]
I want to add data to a Column that corresponds to a string scheme from a `pandas.DataFrame.Column`, where the dataframe column has `NaN` entries.

Code sample to reproduce error:

```python
import pandas as pd

import audformat

db = audformat.Database(name='foo')

df = pd.DataFrame()
df['file'] = ['A', 'B', 'C']
df['bar'] = ['C', 'D', None]
df.set_index('file', inplace=True)

db.schemes['bar'] = audformat.Scheme(labels=['C', 'D'])
db.tables['bar'] = audformat.Table(index=df.index)
db.tables['bar']['bar'] = audformat.Column(scheme_id='bar')
db['bar']['bar'].set(df['bar'])

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/audeering.local/atriant/envs/devaice/lib/python3.6/site-packages/audformat/core/column.py", line 251, in set
    assert_values(values, scheme)
  File "/home/audeering.local/atriant/envs/devaice/lib/python3.6/site-packages/audformat/core/column.py", line 41, in assert_values
    values = np.unique(values)
  File "<__array_function__ internals>", line 6, in unique
  File "/home/audeering.local/atriant/envs/devaice/lib/python3.6/site-packages/numpy/lib/arraysetops.py", line 261, in unique
    ret = _unique1d(ar, return_index, return_inverse, return_counts)
  File "/home/audeering.local/atriant/envs/devaice/lib/python3.6/site-packages/numpy/lib/arraysetops.py", line 322, in _unique1d
    ar.sort()
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

This used to work with `audata`. The offending line is this: https://github.com/audeering/audformat/blob/master/audformat/core/column.py#L41 as `np.unique` does not work with strings and floats. See:

```python
import numpy as np

np.unique(['A', 'B', None])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in unique
  File "/home/audeering.local/atriant/envs/devaice/lib/python3.6/site-packages/numpy/lib/arraysetops.py", line 261, in unique
    ret = _unique1d(ar, return_index, return_inverse, return_counts)
  File "/home/audeering.local/atriant/envs/devaice/lib/python3.6/site-packages/numpy/lib/arraysetops.py", line 322, in _unique1d
    ar.sort()
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

If I pass in the data as `db['bar']['bar'].set(df['bar'].dropna())` instead, then I get a different error because the indices do not match.

@frankenjoe @hagenw if this is confirmed on your side as unwanted behavior, I propose to change the offending line from `np.unique(values)` to `set(values)` to solve it:

```python
>>> set(['A', 'B', None])
{None, 'A', 'B'}
```

**Comment by frankenjoe** [comment]
You can do:

```python
...
bar = df['bar'].dropna()
db['bar']['bar'].set(bar, index=bar.index)
```

**Comment by ATriantafyllopoulos** [comment]
Sorry, I'd missed the latest developments in `audformat`, and I was blind to this extra argument when checking the source code.

The suggestion fixed my problem!
