### ISSUE TITLE
setting values including `nan` and strings to a audformat table, containing string labels, needed to be as a list

### ISSUE THREAD

**Issue by MojganMadadikhaljan** [audeering/audformat#89]
I wanted to set values to a audformat table whose possible labels were string labels as below:
````    
 labels={
           "h": {'category': 'happy'},
           "n": {'category': 'neutral'},
           "b": {'category': 'bored'},
           "a": {'category': 'angry'},
            },
````
The values from dataframe contain `[nan 'b' 'h' 'a' 'n']`. I was getting the error below:
````
Traceback (most recent call last):
  File "create.py", line 409, in <module>
    main()
  File "create.py", line 376, in main
    db['segments']['supposed_emotion'].set(df_segments.supposed_emotion.values)
  File "/home/audeering.local/mmadadi/.local/lib/python3.6/site-packages/audformat/core/column.py", line 251, in set
    assert_values(values, scheme)
  File "/home/audeering.local/mmadadi/.local/lib/python3.6/site-packages/audformat/core/column.py", line 41, in assert_values
    values = np.unique(values)
  File "<__array_function__ internals>", line 6, in unique
  File "/home/audeering.local/mmadadi/.local/lib/python3.6/site-packages/numpy/lib/arraysetops.py", line 261, in unique
    ret = _unique1d(ar, return_index, return_inverse, return_counts)
  File "/home/audeering.local/mmadadi/.local/lib/python3.6/site-packages/numpy/lib/arraysetops.py", line 322, in _unique1d
    ar.sort()
TypeError: '<' not supported between instances of 'str' and 'float'
````

I was able to solve it by, assigning the values to be a list as : 
````
db['segments']['supposed_emotion'].set(list(df_segments.supposed_emotion.values))
````

**Comment by hagenw** [comment]
I encountered the same problem today and didn't understood at the beginning what was the problem.
So, I think we should fix this inside `audformat` to avoid any confusions.

Marking it as bug.
